behaviors:
  CharacterABehavior:   # 左边角色
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2


      memory:
        sequence_length: 32 
        memory_size: 128 

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 30000
    time_horizon: 64
    summary_freq: 1000


  CharacterBBehavior:   # 右边角色
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2


      memory:
        sequence_length: 32
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 30000
    time_horizon: 64
    summary_freq: 1000
