behaviors:
  CharacterABehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4.96
      learning_rate: 1.5e-4
      beta: 1.5e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4

    network_settings:
      normalize: True
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 32
        memory_size: 256

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    self_play:
      save_steps: 10000
      play_against_latest_ratio: 0.5
      swap_steps: 6000
      team_change: 1000000


    max_steps: 100000000 
    time_horizon: 64
    summary_freq: 1000
